version: '3.8'

services:
  db:
    container_name: pgsql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ___
      POSTGRES_PASSWORD: ___
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  secretmessage:
    container_name: secretmessage-go
    env_file: config/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
