---

slack:
  appURL: ""
  signingSecret: ""
  clientID: ""
  clientSecret: ""
  callbackURL: ""
  token: ""
server:
  port: 8080
database:
  name: ""
  host: ""
  username: ""
  password: ""
core:
  cryptoKey: ""
  expirationTime: 60 # SECONDS
