name: CI

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Cloud Run
      uses: stefda/action-cloud-run@v1.0
      with:
        image: gcr.io/secretmessage-2/hello
        service: hello
        project: secretmessage-2
        region: us-central1
        service key: ${{ secrets.GCLOUD_AUTH }}
